### ISSUE TITLE
Pre Marketplace Submission Checklist

### ISSUE THREAD

**Issue by CriticalRespawn** [CriticalRespawn/Blanket#1]
This is a checklist for me so I know what still needs doing (and what's done) before I submit Blanket to the [Ghost Marketplace](https://marketplace.ghost.org/).

- [x] Themes should pass compatibility validation using GScan
- [x] Themes should have a responsive layout and mobile friendly styles, with compatibility for the latest 2 versions of Chrome, Firefox, Safari and IE/Edge
- [x] Themes should make proper use of the asset helper to load all assets
- [x] Themes should include a "Published with Ghost" link to Ghost.org
- [x] Follow the docs
- [x] All parts of the theme should have a clearly linked navigation structure
- [x] All parts of the theme should be accessible with keyboard navigation
- [x] The theme should be tested for colour contrast
- [x] Make good use of tag and author archives
- [x] Create custom styling and layouts for posts which are marked as "featured"
- [x] Ensure good fallbacks when content is empty or unavailable (no featured image, no author bio, no post tags, etc)
- [x] Support upcoming features such as Subscribers (in Labs)
- [x] Themes should have clearly structured data and HTML tags which are search engine friendly
- [x] No SEO "tricks" - clean well structure markup. That's it. And no, we're not going to have a debate about it.
- [x] Images must have alt attributes
- [x] Theme should be built with valid HTML
- [x] Create a sane file structure. 
- [x] Always a space after a property's colon (.e.g, display: block; and not display:block;).
- [x] End all lines with a semi-colon.
or multiple, comma-separated selectors, place each selector on its own line.
- [x] Use tags and elements appropriate for an HTML5 doctype (e.g., self-closing tags)
- [x] HTML attribute order: [ID, class, type, other values]
- [x] 4 spaces for HTML & CSS indentation. Never tabs.
- [x] Double quotes only, never single quotes.
- [x] Adhere to the Recess CSS property order.
- [x] Include extensive base styling for all possible types of content which someone might enter into the Ghost editor.
- [x] Use code comments: Document your work (Check out Casper for a good example)
- [x] Include a detailed ReadMe.md with information about the theme, its features, and where to go for help
- [x] Include a properly formatted package.json
